COMMAND_ENABLE = no
BOOTMAGIC_ENABLE = yes
MAGIC_ENABLE = no
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
CAPS_WORD_ENABLE = yes
REPEAT_KEY_ENABLE = yes
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no

INTROSPECTION_KEYMAP_C = combos.c
SRC += krig.c
SRC += features/achordion.c
SRC += features/flow.c
