/*
 * Kristoffer Gronlund, 2023
 * Preonic
 */
#pragma once

#define RGBLIGHT_LAYERS
#define RGBLIGHT_LAYER_BLINK
#define RGBLIGHT_DEFAULT_MODE RGBLIGHT_MODE_KNIGHT
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_DEFAULT_HUE 222 // rose

#define KRIG_CUSTOM_SHIFT
#define KRIG_CUSTOM_SEQUENCES
#define KRIG_CAPS_WORD
#define KRIG_MOUSE_LAYER
#define KRIG_NUMPAD
#define KRIG_MONOBLOCK
